// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/execgo/v1/execgo.proto

package execgov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskGraph) Reset() {
	*x = TaskGraph{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskGraph) ProtoMessage() {}

func (x *TaskGraph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskGraph.ProtoReflect.Descriptor instead.
func (*TaskGraph) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{0}
}

func (x *TaskGraph) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ParamsJson      string                 `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	DependsOn       []string               `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Retry           int32                  `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	TimeoutMs       int64                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ResultJson      string                 `protobuf:"bytes,8,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Error           string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,10,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,11,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *Task) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *Task) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *Task) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Task) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Task) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

type SubmitTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	TaskIds       []string               `protobuf:"bytes,2,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTasksResponse) Reset() {
	*x = SubmitTasksResponse{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTasksResponse) ProtoMessage() {}

func (x *SubmitTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTasksResponse.ProtoReflect.Descriptor instead.
func (*SubmitTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTasksResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *SubmitTasksResponse) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{5}
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTaskResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Uptime        string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{11}
}

type MetricsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TasksTotal     int64                  `protobuf:"varint,1,opt,name=tasks_total,json=tasksTotal,proto3" json:"tasks_total,omitempty"`
	TasksRunning   int64                  `protobuf:"varint,2,opt,name=tasks_running,json=tasksRunning,proto3" json:"tasks_running,omitempty"`
	TasksSucceeded int64                  `protobuf:"varint,3,opt,name=tasks_succeeded,json=tasksSucceeded,proto3" json:"tasks_succeeded,omitempty"`
	TasksFailed    int64                  `protobuf:"varint,4,opt,name=tasks_failed,json=tasksFailed,proto3" json:"tasks_failed,omitempty"`
	ByType         map[string]int64       `protobuf:"bytes,5,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_execgo_v1_execgo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_execgo_v1_execgo_proto_rawDescGZIP(), []int{12}
}

func (x *MetricsResponse) GetTasksTotal() int64 {
	if x != nil {
		return x.TasksTotal
	}
	return 0
}

func (x *MetricsResponse) GetTasksRunning() int64 {
	if x != nil {
		return x.TasksRunning
	}
	return 0
}

func (x *MetricsResponse) GetTasksSucceeded() int64 {
	if x != nil {
		return x.TasksSucceeded
	}
	return 0
}

func (x *MetricsResponse) GetTasksFailed() int64 {
	if x != nil {
		return x.TasksFailed
	}
	return 0
}

func (x *MetricsResponse) GetByType() map[string]int64 {
	if x != nil {
		return x.ByType
	}
	return nil
}

var File_proto_execgo_v1_execgo_proto protoreflect.FileDescriptor

const file_proto_execgo_v1_execgo_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/execgo/v1/execgo.proto\x12\texecgo.v1\"2\n" +
	"\tTaskGraph\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.execgo.v1.TaskR\x05tasks\"\xc8\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\tR\n" +
	"paramsJson\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\tR\tdependsOn\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x05R\x05retry\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x03R\ttimeoutMs\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vresult_json\x18\b \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12+\n" +
	"\x12created_at_unix_ms\x18\n" +
	" \x01(\x03R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\v \x01(\x03R\x0fupdatedAtUnixMs\"L\n" +
	"\x13SubmitTasksResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x19\n" +
	"\btask_ids\x18\x02 \x03(\tR\ataskIds\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x0fGetTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.execgo.v1.TaskR\x04task\"\x12\n" +
	"\x10ListTasksRequest\":\n" +
	"\x11ListTasksResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.execgo.v1.TaskR\x05tasks\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteTaskResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x0f\n" +
	"\rHealthRequest\"Z\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\"\x10\n" +
	"\x0eMetricsRequest\"\x9f\x02\n" +
	"\x0fMetricsResponse\x12\x1f\n" +
	"\vtasks_total\x18\x01 \x01(\x03R\n" +
	"tasksTotal\x12#\n" +
	"\rtasks_running\x18\x02 \x01(\x03R\ftasksRunning\x12'\n" +
	"\x0ftasks_succeeded\x18\x03 \x01(\x03R\x0etasksSucceeded\x12!\n" +
	"\ftasks_failed\x18\x04 \x01(\x03R\vtasksFailed\x12?\n" +
	"\aby_type\x18\x05 \x03(\v2&.execgo.v1.MetricsResponse.ByTypeEntryR\x06byType\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xa3\x03\n" +
	"\x06ExecGo\x12C\n" +
	"\vSubmitTasks\x12\x14.execgo.v1.TaskGraph\x1a\x1e.execgo.v1.SubmitTasksResponse\x12@\n" +
	"\aGetTask\x12\x19.execgo.v1.GetTaskRequest\x1a\x1a.execgo.v1.GetTaskResponse\x12F\n" +
	"\tListTasks\x12\x1b.execgo.v1.ListTasksRequest\x1a\x1c.execgo.v1.ListTasksResponse\x12I\n" +
	"\n" +
	"DeleteTask\x12\x1c.execgo.v1.DeleteTaskRequest\x1a\x1d.execgo.v1.DeleteTaskResponse\x12=\n" +
	"\x06Health\x12\x18.execgo.v1.HealthRequest\x1a\x19.execgo.v1.HealthResponse\x12@\n" +
	"\aMetrics\x12\x19.execgo.v1.MetricsRequest\x1a\x1a.execgo.v1.MetricsResponseBDZBgithub.com/iammm0/execgo/contrib/grpcapi/pkg/pb/execgo/v1;execgov1b\x06proto3"

var (
	file_proto_execgo_v1_execgo_proto_rawDescOnce sync.Once
	file_proto_execgo_v1_execgo_proto_rawDescData []byte
)

func file_proto_execgo_v1_execgo_proto_rawDescGZIP() []byte {
	file_proto_execgo_v1_execgo_proto_rawDescOnce.Do(func() {
		file_proto_execgo_v1_execgo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_execgo_v1_execgo_proto_rawDesc), len(file_proto_execgo_v1_execgo_proto_rawDesc)))
	})
	return file_proto_execgo_v1_execgo_proto_rawDescData
}

var file_proto_execgo_v1_execgo_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_execgo_v1_execgo_proto_goTypes = []any{
	(*TaskGraph)(nil),           // 0: execgo.v1.TaskGraph
	(*Task)(nil),                // 1: execgo.v1.Task
	(*SubmitTasksResponse)(nil), // 2: execgo.v1.SubmitTasksResponse
	(*GetTaskRequest)(nil),      // 3: execgo.v1.GetTaskRequest
	(*GetTaskResponse)(nil),     // 4: execgo.v1.GetTaskResponse
	(*ListTasksRequest)(nil),    // 5: execgo.v1.ListTasksRequest
	(*ListTasksResponse)(nil),   // 6: execgo.v1.ListTasksResponse
	(*DeleteTaskRequest)(nil),   // 7: execgo.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),  // 8: execgo.v1.DeleteTaskResponse
	(*HealthRequest)(nil),       // 9: execgo.v1.HealthRequest
	(*HealthResponse)(nil),      // 10: execgo.v1.HealthResponse
	(*MetricsRequest)(nil),      // 11: execgo.v1.MetricsRequest
	(*MetricsResponse)(nil),     // 12: execgo.v1.MetricsResponse
	nil,                         // 13: execgo.v1.MetricsResponse.ByTypeEntry
}
var file_proto_execgo_v1_execgo_proto_depIdxs = []int32{
	1,  // 0: execgo.v1.TaskGraph.tasks:type_name -> execgo.v1.Task
	1,  // 1: execgo.v1.GetTaskResponse.task:type_name -> execgo.v1.Task
	1,  // 2: execgo.v1.ListTasksResponse.tasks:type_name -> execgo.v1.Task
	13, // 3: execgo.v1.MetricsResponse.by_type:type_name -> execgo.v1.MetricsResponse.ByTypeEntry
	0,  // 4: execgo.v1.ExecGo.SubmitTasks:input_type -> execgo.v1.TaskGraph
	3,  // 5: execgo.v1.ExecGo.GetTask:input_type -> execgo.v1.GetTaskRequest
	5,  // 6: execgo.v1.ExecGo.ListTasks:input_type -> execgo.v1.ListTasksRequest
	7,  // 7: execgo.v1.ExecGo.DeleteTask:input_type -> execgo.v1.DeleteTaskRequest
	9,  // 8: execgo.v1.ExecGo.Health:input_type -> execgo.v1.HealthRequest
	11, // 9: execgo.v1.ExecGo.Metrics:input_type -> execgo.v1.MetricsRequest
	2,  // 10: execgo.v1.ExecGo.SubmitTasks:output_type -> execgo.v1.SubmitTasksResponse
	4,  // 11: execgo.v1.ExecGo.GetTask:output_type -> execgo.v1.GetTaskResponse
	6,  // 12: execgo.v1.ExecGo.ListTasks:output_type -> execgo.v1.ListTasksResponse
	8,  // 13: execgo.v1.ExecGo.DeleteTask:output_type -> execgo.v1.DeleteTaskResponse
	10, // 14: execgo.v1.ExecGo.Health:output_type -> execgo.v1.HealthResponse
	12, // 15: execgo.v1.ExecGo.Metrics:output_type -> execgo.v1.MetricsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_execgo_v1_execgo_proto_init() }
func file_proto_execgo_v1_execgo_proto_init() {
	if File_proto_execgo_v1_execgo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_execgo_v1_execgo_proto_rawDesc), len(file_proto_execgo_v1_execgo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_execgo_v1_execgo_proto_goTypes,
		DependencyIndexes: file_proto_execgo_v1_execgo_proto_depIdxs,
		MessageInfos:      file_proto_execgo_v1_execgo_proto_msgTypes,
	}.Build()
	File_proto_execgo_v1_execgo_proto = out.File
	file_proto_execgo_v1_execgo_proto_goTypes = nil
	file_proto_execgo_v1_execgo_proto_depIdxs = nil
}
